// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/webcammixer/webcammixer.proto
// DO NOT EDIT!

/*
Package webcammixer is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/webcammixer/webcammixer.proto

It has these top-level messages:
	ImageStream
	VideoDeviceDef
	FrameStream
	LoopbackInfo
	IdleTextRequest
	URL
	CaptureDeviceList
	CaptureDevice
	CountdownRequest
	FrameProvider
	UserImageConverter
	SetTextRequest
	UserImageRequest
	DisplayTextRequest
*/
package webcammixer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ************************************ special userimage provider which does a chain of things to modify streams ******/
type ConverterType int32

const (
	ConverterType_UNDEFINED  ConverterType = 0
	ConverterType_WEBCAM     ConverterType = 1
	ConverterType_LABEL      ConverterType = 2
	ConverterType_EXT_BINARY ConverterType = 3
)

var ConverterType_name = map[int32]string{
	0: "UNDEFINED",
	1: "WEBCAM",
	2: "LABEL",
	3: "EXT_BINARY",
}
var ConverterType_value = map[string]int32{
	"UNDEFINED":  0,
	"WEBCAM":     1,
	"LABEL":      2,
	"EXT_BINARY": 3,
}

func (x ConverterType) String() string {
	return proto.EnumName(ConverterType_name, int32(x))
}
func (ConverterType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// break down one or more images into transportable chunks
type ImageStream struct {
	NextImage bool   `protobuf:"varint,1,opt,name=NextImage" json:"NextImage,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *ImageStream) Reset()                    { *m = ImageStream{} }
func (m *ImageStream) String() string            { return proto.CompactTextString(m) }
func (*ImageStream) ProtoMessage()               {}
func (*ImageStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ImageStream) GetNextImage() bool {
	if m != nil {
		return m.NextImage
	}
	return false
}

func (m *ImageStream) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type VideoDeviceDef struct {
	VideoDeviceName string `protobuf:"bytes,1,opt,name=VideoDeviceName" json:"VideoDeviceName,omitempty"`
}

func (m *VideoDeviceDef) Reset()                    { *m = VideoDeviceDef{} }
func (m *VideoDeviceDef) String() string            { return proto.CompactTextString(m) }
func (*VideoDeviceDef) ProtoMessage()               {}
func (*VideoDeviceDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VideoDeviceDef) GetVideoDeviceName() string {
	if m != nil {
		return m.VideoDeviceName
	}
	return ""
}

// break down one or more frames into transportable chunks
type FrameStream struct {
	NextImage bool   `protobuf:"varint,1,opt,name=NextImage" json:"NextImage,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *FrameStream) Reset()                    { *m = FrameStream{} }
func (m *FrameStream) String() string            { return proto.CompactTextString(m) }
func (*FrameStream) ProtoMessage()               {}
func (*FrameStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FrameStream) GetNextImage() bool {
	if m != nil {
		return m.NextImage
	}
	return false
}

func (m *FrameStream) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoopbackInfo struct {
	DeviceName  string `protobuf:"bytes,1,opt,name=DeviceName" json:"DeviceName,omitempty"`
	Width       uint32 `protobuf:"varint,2,opt,name=Width" json:"Width,omitempty"`
	Height      uint32 `protobuf:"varint,3,opt,name=Height" json:"Height,omitempty"`
	PixelFormat uint32 `protobuf:"varint,4,opt,name=PixelFormat" json:"PixelFormat,omitempty"`
}

func (m *LoopbackInfo) Reset()                    { *m = LoopbackInfo{} }
func (m *LoopbackInfo) String() string            { return proto.CompactTextString(m) }
func (*LoopbackInfo) ProtoMessage()               {}
func (*LoopbackInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoopbackInfo) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *LoopbackInfo) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *LoopbackInfo) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *LoopbackInfo) GetPixelFormat() uint32 {
	if m != nil {
		return m.PixelFormat
	}
	return 0
}

type IdleTextRequest struct {
	Text string `protobuf:"bytes,1,opt,name=Text" json:"Text,omitempty"`
}

func (m *IdleTextRequest) Reset()                    { *m = IdleTextRequest{} }
func (m *IdleTextRequest) String() string            { return proto.CompactTextString(m) }
func (*IdleTextRequest) ProtoMessage()               {}
func (*IdleTextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IdleTextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type URL struct {
	URL string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
}

func (m *URL) Reset()                    { *m = URL{} }
func (m *URL) String() string            { return proto.CompactTextString(m) }
func (*URL) ProtoMessage()               {}
func (*URL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *URL) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type CaptureDeviceList struct {
	Devices []*CaptureDevice `protobuf:"bytes,1,rep,name=Devices" json:"Devices,omitempty"`
}

func (m *CaptureDeviceList) Reset()                    { *m = CaptureDeviceList{} }
func (m *CaptureDeviceList) String() string            { return proto.CompactTextString(m) }
func (*CaptureDeviceList) ProtoMessage()               {}
func (*CaptureDeviceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CaptureDeviceList) GetDevices() []*CaptureDevice {
	if m != nil {
		return m.Devices
	}
	return nil
}

type CaptureDevice struct {
	Device string `protobuf:"bytes,1,opt,name=Device" json:"Device,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Type   uint32 `protobuf:"varint,3,opt,name=Type" json:"Type,omitempty"`
}

func (m *CaptureDevice) Reset()                    { *m = CaptureDevice{} }
func (m *CaptureDevice) String() string            { return proto.CompactTextString(m) }
func (*CaptureDevice) ProtoMessage()               {}
func (*CaptureDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CaptureDevice) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *CaptureDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CaptureDevice) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type CountdownRequest struct {
	Text    string `protobuf:"bytes,1,opt,name=Text" json:"Text,omitempty"`
	Seconds uint32 `protobuf:"varint,2,opt,name=Seconds" json:"Seconds,omitempty"`
}

func (m *CountdownRequest) Reset()                    { *m = CountdownRequest{} }
func (m *CountdownRequest) String() string            { return proto.CompactTextString(m) }
func (*CountdownRequest) ProtoMessage()               {}
func (*CountdownRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CountdownRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CountdownRequest) GetSeconds() uint32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type FrameProvider struct {
	HumanReadableDesc string `protobuf:"bytes,1,opt,name=HumanReadableDesc" json:"HumanReadableDesc,omitempty"`
}

func (m *FrameProvider) Reset()                    { *m = FrameProvider{} }
func (m *FrameProvider) String() string            { return proto.CompactTextString(m) }
func (*FrameProvider) ProtoMessage()               {}
func (*FrameProvider) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FrameProvider) GetHumanReadableDesc() string {
	if m != nil {
		return m.HumanReadableDesc
	}
	return ""
}

type UserImageConverter struct {
	Type   ConverterType  `protobuf:"varint,1,opt,name=Type,enum=webcammixer.ConverterType" json:"Type,omitempty"`
	Text   string         `protobuf:"bytes,2,opt,name=Text" json:"Text,omitempty"`
	Device *CaptureDevice `protobuf:"bytes,3,opt,name=Device" json:"Device,omitempty"`
}

func (m *UserImageConverter) Reset()                    { *m = UserImageConverter{} }
func (m *UserImageConverter) String() string            { return proto.CompactTextString(m) }
func (*UserImageConverter) ProtoMessage()               {}
func (*UserImageConverter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UserImageConverter) GetType() ConverterType {
	if m != nil {
		return m.Type
	}
	return ConverterType_UNDEFINED
}

func (m *UserImageConverter) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *UserImageConverter) GetDevice() *CaptureDevice {
	if m != nil {
		return m.Device
	}
	return nil
}

type SetTextRequest struct {
	Text string `protobuf:"bytes,1,opt,name=Text" json:"Text,omitempty"`
}

func (m *SetTextRequest) Reset()                    { *m = SetTextRequest{} }
func (m *SetTextRequest) String() string            { return proto.CompactTextString(m) }
func (*SetTextRequest) ProtoMessage()               {}
func (*SetTextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SetTextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type UserImageRequest struct {
	Converters []*UserImageConverter `protobuf:"bytes,1,rep,name=Converters" json:"Converters,omitempty"`
}

func (m *UserImageRequest) Reset()                    { *m = UserImageRequest{} }
func (m *UserImageRequest) String() string            { return proto.CompactTextString(m) }
func (*UserImageRequest) ProtoMessage()               {}
func (*UserImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UserImageRequest) GetConverters() []*UserImageConverter {
	if m != nil {
		return m.Converters
	}
	return nil
}

type DisplayTextRequest struct {
	ContinueCamera bool   `protobuf:"varint,1,opt,name=ContinueCamera" json:"ContinueCamera,omitempty"`
	MaxSeconds     uint32 `protobuf:"varint,2,opt,name=MaxSeconds" json:"MaxSeconds,omitempty"`
	Blink          bool   `protobuf:"varint,3,opt,name=Blink" json:"Blink,omitempty"`
	Text           string `protobuf:"bytes,4,opt,name=Text" json:"Text,omitempty"`
}

func (m *DisplayTextRequest) Reset()                    { *m = DisplayTextRequest{} }
func (m *DisplayTextRequest) String() string            { return proto.CompactTextString(m) }
func (*DisplayTextRequest) ProtoMessage()               {}
func (*DisplayTextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DisplayTextRequest) GetContinueCamera() bool {
	if m != nil {
		return m.ContinueCamera
	}
	return false
}

func (m *DisplayTextRequest) GetMaxSeconds() uint32 {
	if m != nil {
		return m.MaxSeconds
	}
	return 0
}

func (m *DisplayTextRequest) GetBlink() bool {
	if m != nil {
		return m.Blink
	}
	return false
}

func (m *DisplayTextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*ImageStream)(nil), "webcammixer.ImageStream")
	proto.RegisterType((*VideoDeviceDef)(nil), "webcammixer.VideoDeviceDef")
	proto.RegisterType((*FrameStream)(nil), "webcammixer.FrameStream")
	proto.RegisterType((*LoopbackInfo)(nil), "webcammixer.LoopbackInfo")
	proto.RegisterType((*IdleTextRequest)(nil), "webcammixer.IdleTextRequest")
	proto.RegisterType((*URL)(nil), "webcammixer.URL")
	proto.RegisterType((*CaptureDeviceList)(nil), "webcammixer.CaptureDeviceList")
	proto.RegisterType((*CaptureDevice)(nil), "webcammixer.CaptureDevice")
	proto.RegisterType((*CountdownRequest)(nil), "webcammixer.CountdownRequest")
	proto.RegisterType((*FrameProvider)(nil), "webcammixer.FrameProvider")
	proto.RegisterType((*UserImageConverter)(nil), "webcammixer.UserImageConverter")
	proto.RegisterType((*SetTextRequest)(nil), "webcammixer.SetTextRequest")
	proto.RegisterType((*UserImageRequest)(nil), "webcammixer.UserImageRequest")
	proto.RegisterType((*DisplayTextRequest)(nil), "webcammixer.DisplayTextRequest")
	proto.RegisterEnum("webcammixer.ConverterType", ConverterType_name, ConverterType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WebCamMixer service

type WebCamMixerClient interface {
	// send one or more images to v4l
	SendImages(ctx context.Context, opts ...grpc.CallOption) (WebCamMixer_SendImagesClient, error)
	//
	// send one or more frames (that is images converted to v4l-out format) to v4l
	// no conversion will be done on this frame.
	// mostly useful for testing converters
	SendFrames(ctx context.Context, opts ...grpc.CallOption) (WebCamMixer_SendFramesClient, error)
	// connect to a LOCAL video device
	SendVideoDevice(ctx context.Context, in *VideoDeviceDef, opts ...grpc.CallOption) (*common.Void, error)
	// connect to any capture source
	SendFromCaptureDevice(ctx context.Context, in *CaptureDevice, opts ...grpc.CallOption) (*common.Void, error)
	// switch to "idle"
	SwitchToIdle(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.Void, error)
	// get loopback config info
	GetLoopbackInfo(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*LoopbackInfo, error)
	// set idle text
	SetIdleText(ctx context.Context, in *IdleTextRequest, opts ...grpc.CallOption) (*common.Void, error)
	// switch to images-client
	SwitchToLiveImages(ctx context.Context, in *URL, opts ...grpc.CallOption) (*common.Void, error)
	// get list of video devices
	GetCaptureDevices(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*CaptureDeviceList, error)
	// rpc display a message and countdown
	SetCountdown(ctx context.Context, in *CountdownRequest, opts ...grpc.CallOption) (*common.Void, error)
	// set a text that frequently changes
	SetUserImage(ctx context.Context, in *UserImageRequest, opts ...grpc.CallOption) (*common.Void, error)
	// stop frequently changing stuff, go back to what it was before starting userimage
	StopUserImage(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.Void, error)
	// set a text for dynamic userimage stuff that frequently changes
	SetUserImageText(ctx context.Context, in *SetTextRequest, opts ...grpc.CallOption) (*common.Void, error)
	// get current frameprovider
	GetCurrentProvider(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*FrameProvider, error)
	// set a dynamic text just for a bit of time, using existing config if possible, e.g. with video overlay. ignored if nobody is watching
	DisplayText(ctx context.Context, in *DisplayTextRequest, opts ...grpc.CallOption) (*common.Void, error)
}

type webCamMixerClient struct {
	cc *grpc.ClientConn
}

func NewWebCamMixerClient(cc *grpc.ClientConn) WebCamMixerClient {
	return &webCamMixerClient{cc}
}

func (c *webCamMixerClient) SendImages(ctx context.Context, opts ...grpc.CallOption) (WebCamMixer_SendImagesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_WebCamMixer_serviceDesc.Streams[0], c.cc, "/webcammixer.WebCamMixer/SendImages", opts...)
	if err != nil {
		return nil, err
	}
	x := &webCamMixerSendImagesClient{stream}
	return x, nil
}

type WebCamMixer_SendImagesClient interface {
	Send(*ImageStream) error
	CloseAndRecv() (*common.Void, error)
	grpc.ClientStream
}

type webCamMixerSendImagesClient struct {
	grpc.ClientStream
}

func (x *webCamMixerSendImagesClient) Send(m *ImageStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *webCamMixerSendImagesClient) CloseAndRecv() (*common.Void, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(common.Void)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webCamMixerClient) SendFrames(ctx context.Context, opts ...grpc.CallOption) (WebCamMixer_SendFramesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_WebCamMixer_serviceDesc.Streams[1], c.cc, "/webcammixer.WebCamMixer/SendFrames", opts...)
	if err != nil {
		return nil, err
	}
	x := &webCamMixerSendFramesClient{stream}
	return x, nil
}

type WebCamMixer_SendFramesClient interface {
	Send(*FrameStream) error
	CloseAndRecv() (*common.Void, error)
	grpc.ClientStream
}

type webCamMixerSendFramesClient struct {
	grpc.ClientStream
}

func (x *webCamMixerSendFramesClient) Send(m *FrameStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *webCamMixerSendFramesClient) CloseAndRecv() (*common.Void, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(common.Void)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webCamMixerClient) SendVideoDevice(ctx context.Context, in *VideoDeviceDef, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/SendVideoDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) SendFromCaptureDevice(ctx context.Context, in *CaptureDevice, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/SendFromCaptureDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) SwitchToIdle(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/SwitchToIdle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) GetLoopbackInfo(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*LoopbackInfo, error) {
	out := new(LoopbackInfo)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/GetLoopbackInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) SetIdleText(ctx context.Context, in *IdleTextRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/SetIdleText", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) SwitchToLiveImages(ctx context.Context, in *URL, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/SwitchToLiveImages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) GetCaptureDevices(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*CaptureDeviceList, error) {
	out := new(CaptureDeviceList)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/GetCaptureDevices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) SetCountdown(ctx context.Context, in *CountdownRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/SetCountdown", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) SetUserImage(ctx context.Context, in *UserImageRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/SetUserImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) StopUserImage(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/StopUserImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) SetUserImageText(ctx context.Context, in *SetTextRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/SetUserImageText", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) GetCurrentProvider(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*FrameProvider, error) {
	out := new(FrameProvider)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/GetCurrentProvider", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webCamMixerClient) DisplayText(ctx context.Context, in *DisplayTextRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/webcammixer.WebCamMixer/DisplayText", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WebCamMixer service

type WebCamMixerServer interface {
	// send one or more images to v4l
	SendImages(WebCamMixer_SendImagesServer) error
	//
	// send one or more frames (that is images converted to v4l-out format) to v4l
	// no conversion will be done on this frame.
	// mostly useful for testing converters
	SendFrames(WebCamMixer_SendFramesServer) error
	// connect to a LOCAL video device
	SendVideoDevice(context.Context, *VideoDeviceDef) (*common.Void, error)
	// connect to any capture source
	SendFromCaptureDevice(context.Context, *CaptureDevice) (*common.Void, error)
	// switch to "idle"
	SwitchToIdle(context.Context, *common.Void) (*common.Void, error)
	// get loopback config info
	GetLoopbackInfo(context.Context, *common.Void) (*LoopbackInfo, error)
	// set idle text
	SetIdleText(context.Context, *IdleTextRequest) (*common.Void, error)
	// switch to images-client
	SwitchToLiveImages(context.Context, *URL) (*common.Void, error)
	// get list of video devices
	GetCaptureDevices(context.Context, *common.Void) (*CaptureDeviceList, error)
	// rpc display a message and countdown
	SetCountdown(context.Context, *CountdownRequest) (*common.Void, error)
	// set a text that frequently changes
	SetUserImage(context.Context, *UserImageRequest) (*common.Void, error)
	// stop frequently changing stuff, go back to what it was before starting userimage
	StopUserImage(context.Context, *common.Void) (*common.Void, error)
	// set a text for dynamic userimage stuff that frequently changes
	SetUserImageText(context.Context, *SetTextRequest) (*common.Void, error)
	// get current frameprovider
	GetCurrentProvider(context.Context, *common.Void) (*FrameProvider, error)
	// set a dynamic text just for a bit of time, using existing config if possible, e.g. with video overlay. ignored if nobody is watching
	DisplayText(context.Context, *DisplayTextRequest) (*common.Void, error)
}

func RegisterWebCamMixerServer(s *grpc.Server, srv WebCamMixerServer) {
	s.RegisterService(&_WebCamMixer_serviceDesc, srv)
}

func _WebCamMixer_SendImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebCamMixerServer).SendImages(&webCamMixerSendImagesServer{stream})
}

type WebCamMixer_SendImagesServer interface {
	SendAndClose(*common.Void) error
	Recv() (*ImageStream, error)
	grpc.ServerStream
}

type webCamMixerSendImagesServer struct {
	grpc.ServerStream
}

func (x *webCamMixerSendImagesServer) SendAndClose(m *common.Void) error {
	return x.ServerStream.SendMsg(m)
}

func (x *webCamMixerSendImagesServer) Recv() (*ImageStream, error) {
	m := new(ImageStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WebCamMixer_SendFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebCamMixerServer).SendFrames(&webCamMixerSendFramesServer{stream})
}

type WebCamMixer_SendFramesServer interface {
	SendAndClose(*common.Void) error
	Recv() (*FrameStream, error)
	grpc.ServerStream
}

type webCamMixerSendFramesServer struct {
	grpc.ServerStream
}

func (x *webCamMixerSendFramesServer) SendAndClose(m *common.Void) error {
	return x.ServerStream.SendMsg(m)
}

func (x *webCamMixerSendFramesServer) Recv() (*FrameStream, error) {
	m := new(FrameStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WebCamMixer_SendVideoDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoDeviceDef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).SendVideoDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/SendVideoDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).SendVideoDevice(ctx, req.(*VideoDeviceDef))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_SendFromCaptureDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureDevice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).SendFromCaptureDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/SendFromCaptureDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).SendFromCaptureDevice(ctx, req.(*CaptureDevice))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_SwitchToIdle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).SwitchToIdle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/SwitchToIdle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).SwitchToIdle(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_GetLoopbackInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).GetLoopbackInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/GetLoopbackInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).GetLoopbackInfo(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_SetIdleText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdleTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).SetIdleText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/SetIdleText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).SetIdleText(ctx, req.(*IdleTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_SwitchToLiveImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(URL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).SwitchToLiveImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/SwitchToLiveImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).SwitchToLiveImages(ctx, req.(*URL))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_GetCaptureDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).GetCaptureDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/GetCaptureDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).GetCaptureDevices(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_SetCountdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).SetCountdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/SetCountdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).SetCountdown(ctx, req.(*CountdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_SetUserImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).SetUserImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/SetUserImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).SetUserImage(ctx, req.(*UserImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_StopUserImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).StopUserImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/StopUserImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).StopUserImage(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_SetUserImageText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).SetUserImageText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/SetUserImageText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).SetUserImageText(ctx, req.(*SetTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_GetCurrentProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).GetCurrentProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/GetCurrentProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).GetCurrentProvider(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebCamMixer_DisplayText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisplayTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebCamMixerServer).DisplayText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webcammixer.WebCamMixer/DisplayText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebCamMixerServer).DisplayText(ctx, req.(*DisplayTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebCamMixer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webcammixer.WebCamMixer",
	HandlerType: (*WebCamMixerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendVideoDevice",
			Handler:    _WebCamMixer_SendVideoDevice_Handler,
		},
		{
			MethodName: "SendFromCaptureDevice",
			Handler:    _WebCamMixer_SendFromCaptureDevice_Handler,
		},
		{
			MethodName: "SwitchToIdle",
			Handler:    _WebCamMixer_SwitchToIdle_Handler,
		},
		{
			MethodName: "GetLoopbackInfo",
			Handler:    _WebCamMixer_GetLoopbackInfo_Handler,
		},
		{
			MethodName: "SetIdleText",
			Handler:    _WebCamMixer_SetIdleText_Handler,
		},
		{
			MethodName: "SwitchToLiveImages",
			Handler:    _WebCamMixer_SwitchToLiveImages_Handler,
		},
		{
			MethodName: "GetCaptureDevices",
			Handler:    _WebCamMixer_GetCaptureDevices_Handler,
		},
		{
			MethodName: "SetCountdown",
			Handler:    _WebCamMixer_SetCountdown_Handler,
		},
		{
			MethodName: "SetUserImage",
			Handler:    _WebCamMixer_SetUserImage_Handler,
		},
		{
			MethodName: "StopUserImage",
			Handler:    _WebCamMixer_StopUserImage_Handler,
		},
		{
			MethodName: "SetUserImageText",
			Handler:    _WebCamMixer_SetUserImageText_Handler,
		},
		{
			MethodName: "GetCurrentProvider",
			Handler:    _WebCamMixer_GetCurrentProvider_Handler,
		},
		{
			MethodName: "DisplayText",
			Handler:    _WebCamMixer_DisplayText_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendImages",
			Handler:       _WebCamMixer_SendImages_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendFrames",
			Handler:       _WebCamMixer_SendFrames_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protos/golang.conradwood.net/apis/webcammixer/webcammixer.proto",
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/webcammixer/webcammixer.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 862 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6f, 0x1b, 0x45,
	0x10, 0xe7, 0x92, 0x34, 0x6d, 0xc6, 0x1f, 0xb9, 0xac, 0xf8, 0x30, 0xa1, 0xb4, 0xd6, 0x09, 0x2a,
	0xab, 0x20, 0x47, 0x0a, 0x15, 0x12, 0xa5, 0x25, 0xf8, 0x2b, 0xad, 0x25, 0xc7, 0x54, 0x77, 0x49,
	0x03, 0xbc, 0xa0, 0xf5, 0xdd, 0xd4, 0x39, 0xd5, 0xb7, 0x6b, 0xee, 0xd6, 0x1f, 0x7d, 0xe1, 0x91,
	0x27, 0xfe, 0x66, 0x84, 0x76, 0xef, 0x23, 0xbb, 0x67, 0x61, 0x50, 0x9f, 0x6e, 0x77, 0x76, 0x7e,
	0x3b, 0x33, 0xbf, 0xd9, 0xf9, 0xe9, 0xe0, 0x6c, 0x1e, 0x73, 0xc1, 0x93, 0x93, 0x29, 0x9f, 0x51,
	0x36, 0x6d, 0xfb, 0x9c, 0xc5, 0x34, 0x58, 0x71, 0x1e, 0xb4, 0x19, 0x8a, 0x13, 0x3a, 0x0f, 0x93,
	0x93, 0x15, 0x4e, 0x7c, 0x1a, 0x45, 0xe1, 0x1a, 0x63, 0x7d, 0xdd, 0x56, 0x48, 0x52, 0xd1, 0x4c,
	0xc7, 0xed, 0x2d, 0xd7, 0xf8, 0x3c, 0x8a, 0x38, 0xcb, 0x3e, 0x29, 0xd8, 0x39, 0x83, 0xca, 0x30,
	0xa2, 0x53, 0xf4, 0x44, 0x8c, 0x34, 0x22, 0xf7, 0xe1, 0x60, 0x8c, 0x6b, 0xa1, 0x4c, 0x0d, 0xab,
	0x69, 0xb5, 0xee, 0xb9, 0xb7, 0x06, 0x42, 0x60, 0xaf, 0x4f, 0x05, 0x6d, 0xec, 0x34, 0xad, 0x56,
	0xd5, 0x55, 0x6b, 0xe7, 0x29, 0xd4, 0x5f, 0x87, 0x01, 0xf2, 0x3e, 0x2e, 0x43, 0x1f, 0xfb, 0xf8,
	0x86, 0xb4, 0xe0, 0x50, 0xb3, 0x8c, 0x69, 0x94, 0xde, 0x74, 0xe0, 0x96, 0xcd, 0x32, 0xf8, 0x79,
	0x4c, 0xa3, 0xf7, 0x0f, 0xfe, 0x07, 0x54, 0x47, 0x9c, 0xcf, 0x27, 0xd4, 0x7f, 0x3b, 0x64, 0x6f,
	0x38, 0x79, 0x00, 0xb0, 0x11, 0x55, 0xb3, 0x90, 0x0f, 0xe1, 0xce, 0x75, 0x18, 0x88, 0x1b, 0x75,
	0x49, 0xcd, 0x4d, 0x37, 0xe4, 0x63, 0xd8, 0x7f, 0x89, 0xe1, 0xf4, 0x46, 0x34, 0x76, 0x95, 0x39,
	0xdb, 0x91, 0x26, 0x54, 0x5e, 0x85, 0x6b, 0x9c, 0x9d, 0xf3, 0x38, 0xa2, 0xa2, 0xb1, 0xa7, 0x0e,
	0x75, 0x93, 0xf3, 0x25, 0x1c, 0x0e, 0x83, 0x19, 0x5e, 0xe2, 0x5a, 0xb8, 0xf8, 0xfb, 0x02, 0x13,
	0x21, 0xd3, 0x94, 0xdb, 0x2c, 0xb8, 0x5a, 0x3b, 0x9f, 0xc0, 0xee, 0x95, 0x3b, 0x22, 0xb6, 0xfa,
	0x64, 0x27, 0x72, 0xe9, 0x0c, 0xe1, 0xa8, 0x47, 0xe7, 0x62, 0x11, 0x63, 0x9a, 0xe4, 0x28, 0x4c,
	0x04, 0x79, 0x02, 0x77, 0xd3, 0x5d, 0xd2, 0xb0, 0x9a, 0xbb, 0xad, 0xca, 0xe9, 0x71, 0x5b, 0x6f,
	0xba, 0x01, 0x70, 0x73, 0x57, 0xe7, 0x27, 0xa8, 0x19, 0x27, 0xb2, 0xaa, 0x74, 0x95, 0x05, 0xcc,
	0x76, 0x32, 0x41, 0xc5, 0xce, 0x4e, 0x9a, 0xa0, 0xe2, 0x45, 0x26, 0xfd, 0x6e, 0x8e, 0x59, 0xfd,
	0x6a, 0xed, 0xfc, 0x08, 0x76, 0x8f, 0x2f, 0x98, 0x08, 0xf8, 0x8a, 0x6d, 0x29, 0x8e, 0x34, 0xe0,
	0xae, 0x87, 0x3e, 0x67, 0x41, 0x92, 0xb1, 0x9a, 0x6f, 0x9d, 0xe7, 0x50, 0x53, 0xed, 0x7d, 0x15,
	0xf3, 0x65, 0x18, 0x60, 0x4c, 0xbe, 0x86, 0xa3, 0x97, 0x8b, 0x88, 0x32, 0x17, 0x69, 0x40, 0x27,
	0x33, 0xec, 0x63, 0xe2, 0x67, 0x77, 0x6d, 0x1e, 0x38, 0x7f, 0x59, 0x40, 0xae, 0x12, 0x8c, 0x55,
	0xfb, 0x7b, 0x9c, 0x2d, 0x31, 0x16, 0x18, 0x93, 0x76, 0x96, 0xab, 0xc4, 0xd5, 0xcb, 0xdc, 0xe4,
	0x5e, 0xd2, 0x23, 0xad, 0xa3, 0xc8, 0x79, 0x47, 0xcb, 0xf9, 0xb4, 0xe0, 0x46, 0x56, 0xbc, 0x9d,
	0xe1, 0xcc, 0xd3, 0xf9, 0x02, 0xea, 0x1e, 0x8a, 0xff, 0x6a, 0xb5, 0x07, 0x76, 0x91, 0x73, 0xee,
	0x77, 0x06, 0x50, 0x24, 0x96, 0xf7, 0xf4, 0xa1, 0x11, 0x71, 0xb3, 0x4c, 0x57, 0x83, 0x38, 0x7f,
	0x5a, 0x40, 0xfa, 0x61, 0x32, 0x9f, 0xd1, 0x77, 0x7a, 0xfc, 0x47, 0x50, 0xef, 0x71, 0x26, 0x42,
	0xb6, 0xc0, 0x1e, 0x8d, 0x30, 0xa6, 0xd9, 0xd0, 0x94, 0xac, 0x72, 0x2a, 0x2e, 0xe8, 0xda, 0x6c,
	0x92, 0x66, 0x91, 0x53, 0xd1, 0x9d, 0x85, 0xec, 0xad, 0x22, 0xe3, 0x9e, 0x9b, 0x6e, 0x8a, 0xea,
	0xf6, 0x6e, 0xab, 0x7b, 0x3c, 0x80, 0x9a, 0x41, 0x31, 0xa9, 0xc1, 0xc1, 0xd5, 0xb8, 0x3f, 0x38,
	0x1f, 0x8e, 0x07, 0x7d, 0xfb, 0x03, 0x02, 0xb0, 0x7f, 0x3d, 0xe8, 0xf6, 0x3a, 0x17, 0xb6, 0x45,
	0x0e, 0xe0, 0xce, 0xa8, 0xd3, 0x1d, 0x8c, 0xec, 0x1d, 0x52, 0x07, 0x18, 0xfc, 0x7c, 0xf9, 0x5b,
	0x77, 0x38, 0xee, 0xb8, 0xbf, 0xd8, 0xbb, 0xa7, 0x7f, 0xef, 0x43, 0xe5, 0x1a, 0x27, 0x3d, 0x1a,
	0x5d, 0xc8, 0xf2, 0xc9, 0xb7, 0x00, 0x1e, 0xb2, 0x40, 0x31, 0x90, 0x90, 0x86, 0x41, 0x8d, 0xa6,
	0x4e, 0xc7, 0xd5, 0x76, 0xa6, 0x5d, 0xaf, 0x79, 0x18, 0xb4, 0xac, 0x1c, 0xa7, 0x1e, 0x59, 0x19,
	0xa7, 0x09, 0xcb, 0x06, 0xee, 0x19, 0x1c, 0x4a, 0x9c, 0x26, 0x47, 0xe4, 0x33, 0x03, 0x6c, 0x2a,
	0x9a, 0x89, 0x27, 0x1d, 0xf8, 0x28, 0x8d, 0xca, 0x23, 0x73, 0xe2, 0xb6, 0xbc, 0xa2, 0xd2, 0x15,
	0x8f, 0xa1, 0xea, 0xad, 0x42, 0xe1, 0xdf, 0x5c, 0x72, 0xa9, 0x1f, 0xc4, 0x38, 0x2d, 0xf9, 0x3e,
	0x85, 0xc3, 0x17, 0x28, 0x0c, 0x99, 0x33, 0xdd, 0x3f, 0x35, 0xc2, 0x1a, 0x8e, 0xdf, 0x41, 0xc5,
	0x43, 0x91, 0x4b, 0x14, 0xb9, 0x6f, 0x32, 0x6b, 0x2a, 0x57, 0x29, 0xec, 0x13, 0x20, 0x79, 0x8a,
	0xa3, 0x70, 0x89, 0x59, 0x6f, 0x6c, 0xf3, 0xd9, 0xba, 0xa3, 0x0d, 0x6e, 0x8e, 0x5e, 0xa0, 0x30,
	0x4a, 0x4f, 0x4a, 0xe9, 0x3e, 0xf8, 0x77, 0x96, 0x94, 0xfc, 0x7d, 0x0f, 0x55, 0x0f, 0x45, 0x21,
	0x3d, 0xe4, 0xf3, 0xd2, 0x84, 0x9b, 0x92, 0x54, 0x8a, 0x9f, 0x82, 0x8b, 0x71, 0x2a, 0x81, 0xcb,
	0x93, 0x59, 0x02, 0x7f, 0x05, 0x35, 0x4f, 0xf0, 0xf9, 0x2d, 0x7a, 0x5b, 0x5b, 0x9e, 0x83, 0xad,
	0x47, 0x52, 0xfc, 0x9a, 0x8f, 0xc8, 0x54, 0x8b, 0x12, 0xfc, 0x07, 0x20, 0x92, 0xa8, 0x45, 0x1c,
	0x23, 0x13, 0x85, 0x40, 0x9a, 0x01, 0x8f, 0x37, 0x1f, 0x74, 0xe1, 0xf9, 0x0c, 0x2a, 0x9a, 0x22,
	0x10, 0x53, 0x4e, 0x36, 0xb5, 0xc2, 0x8c, 0xde, 0x1d, 0xc2, 0x43, 0x86, 0x42, 0xff, 0x49, 0x90,
	0x3f, 0x08, 0xfa, 0x1d, 0xbf, 0x3e, 0xfa, 0x7f, 0xff, 0x23, 0x93, 0x7d, 0xf5, 0x1f, 0xf1, 0xcd,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xef, 0x94, 0x29, 0xc7, 0x08, 0x00, 0x00,
}
